[package]
name = "bend-gpui"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
gpui = { version = "=0.2.2", default-features = false, features = ["runtime_shaders"] }
core-foundation = "=0.10.0"
core-video = { version = "=0.4.3", features = ["metal"] }

[profile.dev]
debug = 0

[profile.release]
debug = 0
