"""Generate balls_flat.bend: balls.bend with the box state unrolled into scalars.

balls.bend keeps a box's 8 balls in a shared list; here they are 32 f32
parameters of one loop, and every pair test is written out (8 x 7 tests a
step, branchless through Bool.pick). The f32 operations and their order are
those of balls.bend and balls.c, so all three print the same line.

    python3 examples/sim/gen_balls_flat.py > examples/sim/balls_flat.bend
"""

NB = 8
FIELDS = ("x", "y", "vx", "vy")


def state(prefix: str = "") -> list[str]:
    return [f"{prefix}{f}{k}" for k in range(NB) for f in FIELDS]


def params(prefix: str = "") -> str:
    return ", ".join(f"+{n}: F32" for n in state(prefix))


def pair(i: int, j: int, acc: str) -> list[str]:
    """Lines adding ball j's impulse on ball i to the running sums of `acc`."""
    t = f"{i}{j}"
    return [
        f"+dx{t} = (x{i} - x{j} : F32)",
        f"+dy{t} = (y{i} - y{j} : F32)",
        f"+d2{t} = (dx{t} * dx{t} + dy{t} * dy{t} : F32)",
        f"+dd{t} = F32.sqrt(d2{t})",
        f"+nx{t} = (dx{t} / dd{t} : F32)",
        f"+ny{t} = (dy{t} / dd{t} : F32)",
        f"+rv{t} = ((vx{i} - vx{j}) * nx{t} + (vy{i} - vy{j}) * ny{t} : F32)",
        # live and closing; a dead pair's NaN normal is never picked
        f"+c{t} = Bool.and(Bool.and(F32.is_lt(0.0, d2{t}), F32.is_lt(d2{t}, "
        f"((0.05 + 0.05) * (0.05 + 0.05) : F32))), F32.is_lt(rv{t}, 0.0))",
        f"+a{t}x = Bool.pick(F32, c{t}, (a{acc}x - rv{t} * nx{t} : F32), a{acc}x)",
        f"+a{t}y = Bool.pick(F32, c{t}, (a{acc}y - rv{t} * ny{t} : F32), a{acc}y)",
        f"+h{t} = Bool.pick(U32, c{t}, U32.inc(h{acc}), h{acc})",
    ]


def step_body() -> list[str]:
    out: list[str] = []
    hits = "in"
    out.append("+hin = hits")
    for i in range(NB):
        acc = f"{i}s"
        out += [f"+a{acc}x = {{0.0 : F32}}", f"+a{acc}y = {{0.0 : F32}}", f"+h{acc} = h{hits}"]
        for j in range(NB):
            if j == i:
                continue
            out += pair(i, j, acc)
            acc = f"{i}{j}"
        out += [
            f"+wx{i} = (vx{i} + a{acc}x : F32)",
            f"+wy{i} = (vy{i} + a{acc}y : F32)",
            # reflect off the walls, then move
            f"+ux{i} = Bool.pick(F32, F32.is_lt(x{i}, 0.05), F32.abs(wx{i}), "
            f"Bool.pick(F32, F32.is_lt((1.0 - 0.05 : F32), x{i}), (0.0 - F32.abs(wx{i}) : F32), wx{i}))",
            f"+uy{i} = Bool.pick(F32, F32.is_lt(y{i}, 0.05), F32.abs(wy{i}), "
            f"Bool.pick(F32, F32.is_lt((1.0 - 0.05 : F32), y{i}), (0.0 - F32.abs(wy{i}) : F32), wy{i}))",
            f"+mx{i} = (x{i} + ux{i} * 0.002 : F32)",
            f"+my{i} = (y{i} + uy{i} * 0.002 : F32)",
        ]
        hits = acc
    nxt = ", ".join(f"m{f[-1]}{k}" if f in ("x", "y") else f"u{f[-1]}{k}"
                    for k in range(NB) for f in FIELDS)
    out.append(f"box.run(p, {nxt}, h{hits})")
    return out


def checksum() -> str:
    terms = [f"(F32.to_u32((x{k} * 65536.0 : F32)) * 31 + F32.to_u32((y{k} * 65536.0 : F32)) : U32)"
             for k in range(NB)]
    expr = terms[0]
    for t in terms[1:]:
        expr = f"U32.add({expr}, {t})"
    return expr


def main() -> None:
    ind = "      "
    body = "\n".join(ind + line for line in step_body())
    balls = ", ".join(f"b{k}" for k in range(NB))
    pats = " ".join(f"Ball{{{', '.join(f'+{f}{k}' for f in FIELDS)}}}" for k in range(NB))
    spawn = ", ".join(f"spawn(s, {k}, {k % 3}.0, {k // 3}.0)" for k in range(NB))
    print(f'''import Base
# GENERATED by gen_balls_flat.py; edit the generator, not this file.
# balls.bend with each box's 8 balls unrolled into 32 f32 parameters of one
# loop: every step writes out the 8 x 7 pair tests (branchless, Bool.pick),
# then reflects off the walls and moves, in the f32 order of balls.bend and
# balls.c, so all three print the same line. Knobs: dep(), steps().

type Ball is Data:
  Ball{{x: F32, y: F32, vx: F32, vy: F32}}

type Out is Data:
  Out{{hits: U32, cs: U32}}

def Out.add(a: Out, b: Out) -> Out:
  match a b:
    case Out{{ah, ac}} Out{{bh, bc}}:
      Out{{(ah + bh : U32), (ac + bc : U32)}}

def prng(+x: U32) -> U32:
  +b = U32.xor(x, U32.shln(x, 13n))
  +d = U32.xor(b, U32.shrn(b, 17n))
  U32.xor(d, U32.shln(d, 5n))

def seed(+i: U32) -> U32:
  U32.xor(U32.mul(U32.inc(i), 2654435761), 1013904223)

def unit(+s: U32) -> F32:
  (U32.to_f32(U32.shrn(s, 8n)) / 16777216.0 : F32)

def spawn(+s: U32, +k: U32, +c: F32, +r: F32) -> Ball:
  +s1 = prng(U32.xor(s, U32.mul(k, 2246822519)))
  +s2 = prng(s1)
  +s3 = prng(s2)
  +s4 = prng(s3)
  +gx = (0.2 + 0.3 * c : F32)
  +gy = (0.2 + 0.3 * r : F32)
  Ball{{(gx + (unit(s1) - 0.5) * 0.1 : F32), (gy + (unit(s2) - 0.5) * 0.1 : F32),
       (unit(s3) - 0.5 : F32), (unit(s4) - 0.5 : F32)}}

def box.run(k: Nat, {params()}, +hits: U32) -> Out:
  match k:
    case 0n:
      Out{{hits, {checksum()}}}
    case 1n+p:
{body}

def box.start(+k: Nat, {", ".join(f"b{i}: Ball" for i in range(NB))}) -> Out:
  match {balls}:
    case {pats}:
      box.run(k, {", ".join(state())}, 0)

def box(+k: Nat, +i: U32) -> Out:
  +s = seed(i)
  box.start(k, {spawn})

def tree(+d: Nat, +k: Nat, +i: U32) -> Out:
  match d:
    case 0n:
      box(k, i)
    case 1n+p:
      a b = tree(p, k, i) tree(p, k, U32.add(i, U32.shln(1, p)))
      Out.add(a, b)

def Out.show(o: Out) -> String:
  match o:
    case Out{{h, c}}:
      "contacts=" ++ U32.show(h) ++ " checksum=" ++ U32.show(c)

def dep() -> Nat:
  12n

def steps() -> Nat:
  4096n

def main() -> IO(Unit):
  IO.print(Out.show(tree(dep(), steps(), 0)))''')


if __name__ == "__main__":
    main()
